#!/usr/bin/env node
/* Generates docs/DATA-MODEL.md — a mermaid ER diagram + field tables derived
   from the config. The config already declares every field and relation, so
   the diagram is free and can never drift: regenerate after config changes
   (`npm run model`). CONFIG_PATH is honored like the server does. */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const cfgPath = process.env.CONFIG_PATH || "starter.config.json";
const CONFIG = JSON.parse(readFileSync(path.isAbsolute(cfgPath) ? cfgPath : path.join(ROOT, cfgPath), "utf8"));

const lines = ["erDiagram"];
for (const o of CONFIG.objects) {
  lines.push(`  ${o.key} {`);
  for (const f of o.fields) {
    const flags = [f.primary ? "PK" : null].filter(Boolean).join(" ");
    lines.push(`    ${f.type.replace(/[^a-z]/g, "_")} ${f.key} ${flags ? `"${flags}"` : ""}`.trimEnd());
  }
  lines.push("  }");
}
for (const o of CONFIG.objects) {
  for (const f of o.fields) {
    if (f.type === "relation" && f.relation) {
      lines.push(`  ${f.relation} ||--o{ ${o.key} : "${f.key}"`);
    }
  }
}

const tables = CONFIG.objects
  .map((o) => {
    const rows = o.fields
      .map((f) => {
        const extra = [
          f.primary ? "primary" : null,
          f.options ? `options: ${f.options.join(" / ")}` : null,
          f.relation ? `→ ${f.relation}` : null,
          f.primitive ? `enrich: ${f.primitive.label ?? f.primitive.kind}` : null,
          o.stageField === f.key ? "stage (board columns)" : null,
        ].filter(Boolean).join(" · ");
        return `| \`${f.key}\` | ${f.type} | ${extra} |`;
      })
      .join("\n");
    return `### ${o.label} (\`${o.key}\`)\nDefault view: ${o.defaultView}${o.stageField ? ` · stage field: \`${o.stageField}\`` : ""}\n\n| Field | Type | Notes |\n|---|---|---|\n${rows}`;
  })
  .join("\n\n");

const md = `# Data model — derived from \`${cfgPath}\`

Generated by \`npm run model\`. Do not edit by hand — change the config and regenerate.

\`\`\`mermaid
${lines.join("\n")}
\`\`\`

${tables}

Users directory: ${CONFIG.users?.length ? CONFIG.users.map((u) => `\`${u}\``).join(", ") : "none configured"} (drives \`user\`-type fields).
`;

writeFileSync(path.join(ROOT, "docs", "DATA-MODEL.md"), md);
console.log(`[gen-model] docs/DATA-MODEL.md ← ${CONFIG.objects.length} objects from ${cfgPath}`);
